// Auto-generated by GARS for iTerm2 compatibility
#import "CATiledLayer.h"
#import <Foundation/Foundation.h>

@implementation CATiledLayer

- (instancetype)init {
    self = [super init];
    if (self) {
        _levelsOfDetail = 1;
        _levelsOfDetailBias = 0;
        _tileSize = CGSizeMake(256, 256);
        NSLog(@"[GARS] CATiledLayer initialized (stub)");
    }
    return self;
}

+ (CFTimeInterval)fadeDuration {
    return 0.25;
}

- (void)setNeedsDisplayInRect:(CGRect)rect {
    [super setNeedsDisplayInRect:rect];
}

@end
