// Auto-generated by GARS for iTerm2 compatibility
#import <QuartzCore/CALayer.h>

@interface CATiledLayer : CALayer

@property size_t levelsOfDetail;
@property size_t levelsOfDetailBias;
@property CGSize tileSize;

+ (CFTimeInterval)fadeDuration;

@end
