#import <CoreText/CTFont.h>

CORETEXT_EXPORT const CFStringRef kCTLigatureAttributeName;
CORETEXT_EXPORT const CFStringRef kCTUnderlineStyleAttributeName;
CORETEXT_EXPORT const CFStringRef kCTFontAttributeName;
CORETEXT_EXPORT const CFStringRef kCTForegroundColorAttributeName;
CORETEXT_EXPORT const CFStringRef kCTForegroundColorFromContextAttributeName;
CORETEXT_EXPORT const CFStringRef kCTStrokeWidthAttributeName;
CORETEXT_EXPORT const CFStringRef kCTStrokeColorAttributeName;
CORETEXT_EXPORT const CFStringRef kCTParagraphStyleAttributeName;
CORETEXT_EXPORT const CFStringRef kCTKernAttributeName;
CORETEXT_EXPORT const CFStringRef kCTLanguageAttributeName;
CORETEXT_EXPORT const CFStringRef kCTVerticalFormsAttributeName;

